services:
  - type: web
    name: hsr-guide-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
    healthCheckPath: /
    autoDeploy: true
